[tool.isort]
extend_skip = ["data"]
profile = "black"

[tool.black]
extend-exclude = '''
    (/data|/.venv)
'''

[tool.pip-tools]
no-emit-index-url = true

[tool.pytest.ini_options]
addopts = "--rootdir=."
pythonpath = ["src"]
testpaths = ["test", "data/adapter"]
