services:
  MessageSyncer:
    container_name: MessageSyncer
    image: ghcr.io/messagesyncer/messagesyncer:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai # Change to the time zone you want
    ports:
      - 11589:11589
    volumes:
      - ../data/data:/MessageSyncer/data
      - ../data/getters:/MessageSyncer/src/getters
      - ../data/pushers:/MessageSyncer/src/pushers