name: Generate Changelog

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: |
          pip install evative7-changeloggen
          changelog .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
